### ISSUE TITLE
Color mix up

### ISSUE THREAD

**Issue by raae** [triozer/framer-toolbox#82]
The segments were blue like the buttons until this week when I believe Framer's primary color changed. Could it be that the button picks up the CSS variable for primary, while the color for the segment does not?

![CleanShot 2024-09-24 at 11 52 23 2@2x](https://github.com/user-attachments/assets/9999082e-5427-4a48-9293-feddabb6c96c)
![CleanShot 2024-09-24 at 11 51 59 2@2x](https://github.com/user-attachments/assets/b62c18b4-9b4f-4be7-b6af-ab154ae266bb)

**Comment by triozer** [comment]
That's a nice catch, yeah, so basically the SegmentedControls text color was fixed, it was independent of Framer's tint.

Maybe we should always use Framer's Fresco vars, I'm still unsure about that.

This specific issue should be fixed by #83.
